"""TrafficMind traffic rules engine package."""

from services.rules.config import RulesSettings, get_rules_settings
from services.rules.engine import RulesEngine
from services.rules.schemas import (
    BusStopOccupationRuleConfig,
    Explanation,
    IllegalParkingRuleConfig,
    LineGeometry,
    LineCrossingRuleConfig,
    NoStoppingRuleConfig,
    PedestrianOnRedRuleConfig,
    PolygonGeometry,
    PreViolationRecord,
    RedLightRuleConfig,
    RuleConfig,
    RuleEvaluationResult,
    RuleType,
    SceneContext,
    SceneSignalState,
    StalledVehicleRuleConfig,
    StopLineCrossingRuleConfig,
    TrafficLightState,
    ViolationLifecycleStage,
    ViolationRecord,
    WrongDirectionRuleConfig,
    ZoneConfig,
    ZoneDwellTimeRuleConfig,
    ZoneEntryRuleConfig,
    parse_zone_config,
)

__all__ = [
    "BusStopOccupationRuleConfig",
    "Explanation",
    "IllegalParkingRuleConfig",
    "LineGeometry",
    "LineCrossingRuleConfig",
    "NoStoppingRuleConfig",
    "PedestrianOnRedRuleConfig",
    "PolygonGeometry",
    "PreViolationRecord",
    "RedLightRuleConfig",
    "RuleConfig",
    "RuleEvaluationResult",
    "RuleType",
    "RulesEngine",
    "RulesSettings",
    "SceneContext",
    "SceneSignalState",
    "StalledVehicleRuleConfig",
    "StopLineCrossingRuleConfig",
    "TrafficLightState",
    "ViolationLifecycleStage",
    "ViolationRecord",
    "WrongDirectionRuleConfig",
    "ZoneConfig",
    "ZoneDwellTimeRuleConfig",
    "ZoneEntryRuleConfig",
    "get_rules_settings",
    "parse_zone_config",
]
