"""Render commit-safe environment profiles into concrete local env files."""

from __future__ import annotations

import argparse
from pathlib import Path

from dotenv import dotenv_values

REPO_ROOT = Path(__file__).resolve().parents[2]
PROFILE_SOURCES = {
    "local": REPO_ROOT / ".env.example",
    "dev": REPO_ROOT / "infra" / "env" / "dev.env.example",
    "staging": REPO_ROOT / "infra" / "env" / "staging.env.example",
    "prod": REPO_ROOT / "infra" / "env" / "prod.env.example",
}
FRONTEND_ENV_KEYS = [
    "TRAFFICMIND_API_BASE_URL",
    "NEXT_PUBLIC_TRAFFICMIND_API_BASE_URL",
    "NEXT_PUBLIC_API_BASE_URL",
    "TRAFFICMIND_SPATIAL_LOOKBACK_DAYS",
    "NEXT_PUBLIC_TRAFFICMIND_SPATIAL_LOOKBACK_DAYS",
    "TRAFFICMIND_SPATIAL_TOP_N",
    "NEXT_PUBLIC_TRAFFICMIND_SPATIAL_TOP_N",
    "NEXT_PUBLIC_MAP_PROVIDER",
    "NEXT_PUBLIC_MAP_STYLE_URL",
    "NEXT_PUBLIC_MAP_ACCESS_TOKEN",
]


def _build_parser() -> argparse.ArgumentParser:
    parser = argparse.ArgumentParser(
        description="Render a TrafficMind env profile template into a target file."
    )
    parser.add_argument("--profile", choices=sorted(PROFILE_SOURCES), default="local")
    parser.add_argument("--output", default=str(REPO_ROOT / ".env"))
    parser.add_argument(
        "--frontend-output",
        default=None,
        help=(
            "Optional path to also render a frontend/.env.local-style file with the "
            "frontend-facing variables from the same profile."
        ),
    )
    parser.add_argument(
        "--force",
        action="store_true",
        help="Overwrite the output file if it already exists.",
    )
    return parser


def _resolve_output_path(path: str) -> Path:
    output_path = Path(path)
    if not output_path.is_absolute():
        output_path = (REPO_ROOT / output_path).resolve()
    return output_path


def _write_text_file(path: Path, content: str, *, force: bool) -> None:
    if path.exists() and not force:
        raise FileExistsError(path)
    path.parent.mkdir(parents=True, exist_ok=True)
    path.write_text(content, encoding="utf-8")


def _render_frontend_env(source: Path) -> str:
    values = dotenv_values(source)
    lines = [
        "# Generated by infra/scripts/render_env.py",
        "# This file is intentionally frontend-scoped for Next.js local development.",
        "",
    ]

    for key in FRONTEND_ENV_KEYS:
        value = values.get(key)
        if value is None:
            continue
        lines.append(f"{key}={value}")

    lines.append("")
    return "\n".join(lines)


def main(argv: list[str] | None = None) -> int:
    parser = _build_parser()
    args = parser.parse_args(argv)

    source = PROFILE_SOURCES[args.profile]
    output_path = _resolve_output_path(args.output)

    try:
        _write_text_file(output_path, source.read_text(encoding="utf-8"), force=args.force)
    except FileExistsError:
        parser.error(f"Output file already exists: {output_path}. Use --force to overwrite it.")

    print(f"Rendered {args.profile} profile from {source} to {output_path}")

    if args.frontend_output:
        frontend_output_path = _resolve_output_path(args.frontend_output)
        try:
            _write_text_file(
                frontend_output_path,
                _render_frontend_env(source),
                force=args.force,
            )
        except FileExistsError:
            parser.error(
                "Frontend output file already exists: "
                f"{frontend_output_path}. Use --force to overwrite it."
            )
        print(
            "Rendered frontend env from "
            f"{source} to {frontend_output_path}"
        )

    return 0


if __name__ == "__main__":
    raise SystemExit(main())
