import Link from "next/link";

export const metadata = { title: "Help | TrafficMind" };

export default function HelpPage() {
  const sectionClass =
    "rounded-[2rem] border border-[rgba(23,57,69,0.12)] bg-[rgba(255,255,255,0.82)] p-6 shadow-[0_18px_40px_rgba(18,32,41,0.06)]";

  return (
    <main className="mx-auto flex min-h-screen w-full max-w-6xl flex-col gap-6 px-4 py-8 sm:px-6">
      {/* ── Hero ─────────────────────────────────────── */}
      <section className="rounded-[2rem] border border-[rgba(23,57,69,0.12)] bg-[linear-gradient(135deg,rgba(244,238,224,0.94),rgba(231,242,244,0.92))] p-8 shadow-[0_24px_60px_rgba(18,32,41,0.08)]">
        <p className="text-[0.75rem] font-semibold uppercase tracking-[0.24em] text-[rgba(19,32,41,0.56)]">Operator Guide</p>
        <h1 className="mt-3 text-4xl font-semibold tracking-[-0.06em] text-[var(--color-ink)]">Help &amp; Reference</h1>
        <p className="mt-4 max-w-3xl text-base leading-7 text-[rgba(19,32,41,0.74)]">
          Quick reference for the TrafficMind operator interface. Use this page to understand key concepts, navigate the system, and find answers to common questions.
        </p>
      </section>

      {/* ── Navigation guide ────────────────────────────── */}
      <section className={sectionClass}>
        <p className="text-[0.75rem] font-semibold uppercase tracking-[0.24em] text-[rgba(19,32,41,0.56)]">Getting Around</p>
        <div className="mt-4 space-y-3 text-sm leading-6 text-[rgba(19,32,41,0.74)]">
          <div className="flex items-start gap-3">
            <span className="mt-0.5 shrink-0 rounded-full bg-[var(--color-ink)] px-2.5 py-0.5 text-xs font-medium text-[var(--color-paper)]">Dashboard</span>
            <p>Your starting point. Shows the camera network map, operational stats, location-level incident summaries, and recent activity feeds. <Link href="/" className="underline underline-offset-2 hover:text-[var(--color-ink)]">Go to Dashboard</Link></p>
          </div>
          <div className="flex items-start gap-3">
            <span className="mt-0.5 shrink-0 rounded-full bg-[var(--color-ink)] px-2.5 py-0.5 text-xs font-medium text-[var(--color-paper)]">Cases</span>
            <p>Review flagged violations and supporting detections. Filter by time, type, status, or camera. Each violation is a case that can be reviewed and resolved. <Link href="/cases" className="underline underline-offset-2 hover:text-[var(--color-ink)]">Go to Cases</Link></p>
          </div>
          <div className="flex items-start gap-3">
            <span className="mt-0.5 shrink-0 rounded-full bg-[var(--color-ink)] px-2.5 py-0.5 text-xs font-medium text-[var(--color-paper)]">Alerts</span>
            <p>Operational alerts generated by policy rules — violations, health issues, watchlist hits, and more. Filter by status, severity, or source. <Link href="/alerts" className="underline underline-offset-2 hover:text-[var(--color-ink)]">Go to Alerts</Link></p>
          </div>
          <div className="flex items-start gap-3">
            <span className="mt-0.5 shrink-0 rounded-full bg-[var(--color-ink)] px-2.5 py-0.5 text-xs font-medium text-[var(--color-paper)]">Cameras</span>
            <p>Browse all registered cameras, check their status, and view configuration details including streams, zones, and calibration. <Link href="/cameras" className="underline underline-offset-2 hover:text-[var(--color-ink)]">Go to Cameras</Link></p>
          </div>
          <div className="flex items-start gap-3">
            <span className="mt-0.5 shrink-0 rounded-full bg-[var(--color-ink)] px-2.5 py-0.5 text-xs font-medium text-[var(--color-paper)]">Reports</span>
            <p>Exported evidence bundles for audit and review. Browse completed and pending exports by subject type. <Link href="/reports" className="underline underline-offset-2 hover:text-[var(--color-ink)]">Go to Reports</Link></p>
          </div>
          <div className="flex items-start gap-3">
            <span className="mt-0.5 shrink-0 rounded-full bg-[rgba(19,32,41,0.72)] px-2.5 py-0.5 text-xs font-medium text-[var(--color-paper)]">Evaluation</span>
            <p>Model performance results from benchmark tests. Shows detection accuracy, tracking continuity, OCR quality, rule validation, and signal classification metrics with plain-English summaries. <Link href="/evaluation" className="underline underline-offset-2 hover:text-[var(--color-ink)]">Go to Evaluation</Link></p>
          </div>
          <div className="flex items-start gap-3">
            <span className="mt-0.5 shrink-0 rounded-full bg-[rgba(19,32,41,0.72)] px-2.5 py-0.5 text-xs font-medium text-[var(--color-paper)]">Settings</span>
            <p>Access control policy, role permissions, and admin tools. Managed by system administrators. <Link href="/settings" className="underline underline-offset-2 hover:text-[var(--color-ink)]">Go to Settings</Link></p>
          </div>
        </div>
      </section>

      {/* ── Glossary ────────────────────────────────────── */}
      <section className={sectionClass}>
        <p className="text-[0.75rem] font-semibold uppercase tracking-[0.24em] text-[rgba(19,32,41,0.56)]">Glossary</p>
        <div className="mt-4 divide-y divide-[rgba(23,57,69,0.08)]">
          {GLOSSARY.map(({ term, definition }) => (
            <div key={term} className="py-3 first:pt-0 last:pb-0">
              <dt className="font-semibold text-[var(--color-ink)]">{term}</dt>
              <dd className="mt-1 text-sm leading-6 text-[rgba(19,32,41,0.72)]">{definition}</dd>
            </div>
          ))}
        </div>
      </section>

      {/* ── Severity guide ──────────────────────────────── */}
      <section className={sectionClass}>
        <p className="text-[0.75rem] font-semibold uppercase tracking-[0.24em] text-[rgba(19,32,41,0.56)]">Severity Levels</p>
        <div className="mt-4 grid gap-3 sm:grid-cols-2 lg:grid-cols-4">
          {SEVERITY_GUIDE.map(({ level, color, description }) => (
            <div key={level} className="rounded-[1.5rem] bg-[rgba(243,237,228,0.72)] p-4">
              <span className={`inline-block rounded-full px-3 py-1 text-xs font-semibold uppercase tracking-[0.16em] ${color}`}>
                {level}
              </span>
              <p className="mt-2 text-sm leading-6 text-[rgba(19,32,41,0.72)]">{description}</p>
            </div>
          ))}
        </div>
      </section>

      {/* ── Common tasks ────────────────────────────────── */}
      <section className={sectionClass}>
        <p className="text-[0.75rem] font-semibold uppercase tracking-[0.24em] text-[rgba(19,32,41,0.56)]">Common Tasks</p>
        <div className="mt-4 space-y-4 text-sm leading-6 text-[rgba(19,32,41,0.74)]">
          <div>
            <p className="font-semibold text-[var(--color-ink)]">Review a violation case</p>
            <p className="mt-1">Go to <Link href="/cases" className="underline underline-offset-2 hover:text-[var(--color-ink)]">Cases</Link>, find the violation in the Review Queue, check severity and summary, then update its status as appropriate.</p>
          </div>
          <div>
            <p className="font-semibold text-[var(--color-ink)]">Filter cases by camera</p>
            <p className="mt-1">From the <Link href="/" className="underline underline-offset-2 hover:text-[var(--color-ink)]">Dashboard</Link>, click a camera marker, then select &quot;View incidents&quot; to see cases scoped to that camera.</p>
          </div>
          <div>
            <p className="font-semibold text-[var(--color-ink)]">Check camera health</p>
            <p className="mt-1">Click a camera marker on the Dashboard map, then select &quot;Camera details&quot; to see stream health, zone configuration, and connection status.</p>
          </div>
          <div>
            <p className="font-semibold text-[var(--color-ink)]">Understand an alert</p>
            <p className="mt-1">Go to <Link href="/alerts" className="underline underline-offset-2 hover:text-[var(--color-ink)]">Alerts</Link> and filter by status or source. Each alert shows the triggering condition, severity, occurrence count, and current state.</p>
          </div>
        </div>
      </section>
    </main>
  );
}

const GLOSSARY = [
  { term: "Violation", definition: "A confirmed or suspected traffic rule breach detected by the system — for example, running a red light, speeding, or an illegal turn. Each violation becomes a reviewable case." },
  { term: "Detection", definition: "A raw camera observation of an object (vehicle, pedestrian, etc.) at a specific time and location. Detections are the building blocks that feed the violation pipeline." },
  { term: "Case", definition: "A violation that has been flagged for operator review. Cases progress through statuses: Open → Under Review → Confirmed or Dismissed." },
  { term: "Alert", definition: "An operational notification raised when a policy rule is triggered — for example, a high-severity violation, a camera health drop, or a watchlist match. Alerts can be acknowledged, escalated, resolved, or suppressed." },
  { term: "Zone", definition: "A defined area within a camera frame where events are monitored. Zones mark stop lines, crosswalks, lanes, or other regions of interest." },
  { term: "Stream", definition: "A video feed connection between a camera and the system. Streams carry the frames that are processed for detections." },
  { term: "Junction", definition: "An intersection or location where one or more cameras are deployed. The dashboard groups cameras by shared junction names." },
  { term: "Escalation", definition: "When an unacknowledged alert is automatically promoted to the next notification level. Escalation policies define timing and routing targets." },
  { term: "Export", definition: "A packaged evidence bundle containing all relevant data for a case — structured records, review history, and audit trail — ready for compliance and legal review." },
  { term: "Severity", definition: "A priority level assigned to violations and alerts: Critical, High, Medium, Low, or Info. Severity determines how prominently items appear and how quickly they should be addressed." },
  { term: "Precision", definition: "The percentage of the system's detections that were correct. High precision means few false alarms — the system rarely flags something that isn't there." },
  { term: "Recall", definition: "The percentage of real objects the system successfully detected. High recall means few missed objects — the system rarely fails to notice something that is there." },
  { term: "IoU (Intersection over Union)", definition: "A measure of overlap quality between the system's detection box and the actual object location. Ranges from 0 to 1 — closer to 1 means the detection closely matches reality." },
  { term: "Continuity Score", definition: "How consistently the system maintains a single identity for each tracked object over time. A high score means vehicles are tracked smoothly without losing or swapping identities." },
  { term: "ID Switch", definition: "When a tracked object is mistakenly assigned a new identity mid-track — for example, a vehicle being counted as two different vehicles. Fewer ID switches is better; zero is ideal." },
  { term: "Benchmark Test", definition: "A controlled evaluation using known test data to measure system accuracy. Results on the Evaluation page come from benchmarks, not live production traffic." },
] as const;

const SEVERITY_GUIDE = [
  { level: "Critical", color: "bg-[rgba(240,90,79,0.14)] text-[var(--color-danger)]", description: "Immediate attention required. Safety-critical events such as wrong-way driving or pedestrian conflicts." },
  { level: "High", color: "bg-[rgba(240,90,79,0.10)] text-[var(--color-danger)]", description: "Urgent review needed. Red light violations, significant speeding, or camera system failures." },
  { level: "Medium", color: "bg-[rgba(226,176,71,0.16)] text-[var(--color-warning-ink)]", description: "Should be reviewed during the current shift. Moderate violations or health degradation." },
  { level: "Low", color: "bg-[rgba(56,183,118,0.14)] text-[var(--color-ok-ink)]", description: "Informational. Minor infractions or routine detections that may not require immediate action." },
] as const;
